<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_startDate</name>
   <tag></tag>
   <elementGuidId>2e584b1f-3312-40e2-b45f-014fadc64c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'startDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#startDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f47a6b5e-aef6-4cd4-a0b6-797674c1aa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e07774fe-4b81-404d-9611-ab34cf4ff827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>112887a0-8f8b-4644-8d74-07dc4650b83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b538fb1cf2983e899292a65c732bccc1</value>
      <webElementGuid>990a7426-3c9c-46a0-9104-c915be56e359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'startDate']</value>
      <webElementGuid>14da75b3-5dba-49f9-afc1-4a2d7582ed85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'startDate']</value>
      <webElementGuid>40d598b6-63b5-4b8a-ab9d-747772945892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'startDate']</value>
      <webElementGuid>68122ba1-912b-4493-adb8-2a78e4b03bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
