<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnSaveCategory</name>
   <tag></tag>
   <elementGuidId>7f19fd6c-9246-495f-b07c-540a6330b7bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnSaveCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Lưu danh mục&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42468c2a-c9de-4162-b9f0-b44857c8049e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>87d0e5ee-3a8f-49af-b2da-0e7e408959c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveCategory</value>
      <webElementGuid>1fe534bb-8704-4ddd-a97d-7995b8171e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu danh mục</value>
      <webElementGuid>f11a7acf-e30b-4bb4-8b89-f69e422bddf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4ae8bd964e79897cc298a85154f06254</value>
      <webElementGuid>d1043c31-dde5-49fc-a9c8-5db9537d1ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveCategory']</value>
      <webElementGuid>a80ffd18-5956-40c2-a1b5-9aefbf057eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveCategory']</value>
      <webElementGuid>06f97891-7e19-4373-a625-25d505758bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveCategory' and (text() = 'Lưu danh mục' or . = 'Lưu danh mục')]</value>
      <webElementGuid>aad69c2e-9bdc-4c64-83e1-28662b43e0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
