analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3508877,"name"\:"Cellphone Shop Trial \#3508877","teamId"\:3508469,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3513813,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3508469,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
