<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnResetFilter</name>
   <tag></tag>
   <elementGuidId>f763373b-b24d-4a7c-ab4f-a59e394b4595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnResetFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnResetFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đặt lại&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>282a41f4-653f-47f1-87b4-f4115d15ad7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-ghost</value>
      <webElementGuid>783ba991-9dc4-4804-9dca-5a6ddfa72df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnResetFilter</value>
      <webElementGuid>65a27ba3-fb2e-4632-bbcc-b15fd4ae50fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt lại</value>
      <webElementGuid>2eebb1c8-1710-4c06-94c8-bb2ce9bd77ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cbeb48adc72f1ac6d8a58a48d41886c9</value>
      <webElementGuid>714667ee-1e35-4544-afcb-6e6edcaf7f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnResetFilter']</value>
      <webElementGuid>cf837ebf-f8a6-442f-a2ed-80c03b084325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnResetFilter']</value>
      <webElementGuid>7e23ac38-c3e5-47a1-97ad-73328aac9773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnResetFilter' and (text() = 'Đặt lại' or . = 'Đặt lại')]</value>
      <webElementGuid>2e5181be-a544-48af-9ddb-fcaf1c4779f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
