<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email chnh</name>
   <tag></tag>
   <elementGuidId>0a149bd5-987e-4133-97b8-2fb473e991f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailChinh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'emailChinh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email chính&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b58e5cd-3f69-4d6a-b23f-e474df88880b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>02eb3a45-bc67-424c-bc5e-d39651d4b36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailChinh</value>
      <webElementGuid>3bb2d2cc-4edb-4544-94c7-023bc34dbad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tranthib@gmail.com</value>
      <webElementGuid>8b42498d-5021-4bc0-8684-c8d57f615ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-319c33096a3bee3b746a39a08df1d587</value>
      <webElementGuid>e8f20754-e5b1-43f7-80fa-ea3129517a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'emailChinh']</value>
      <webElementGuid>57334bda-307b-4b22-b5e6-5113ece00bb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'emailChinh']</value>
      <webElementGuid>cd25391e-5f42-4cce-ac41-80d1c6c7924b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailChinh']</value>
      <webElementGuid>91a6370e-7d42-49dd-a02d-fd3ebe1fe74c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
