<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lc sn phm</name>
   <tag></tag>
   <elementGuidId>22b7cc95-fb15-4c89-9bb8-cb910f1f01b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.filter-apply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' filter-apply ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Lọc sản phẩm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>765bd361-8f95-45ee-999b-2d0a4a1f94fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-apply</value>
      <webElementGuid>562d8540-97f3-412a-9975-bed5cb7ab2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>applyFilters()</value>
      <webElementGuid>3b6aec32-c475-4a94-af42-a8f8460ccb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lọc sản phẩm</value>
      <webElementGuid>e2ce72bd-e6ab-4c94-aa5e-313c7b159678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e5a0ce4e4ff54b5c48bc4c8a1c1d283a</value>
      <webElementGuid>5fa9c08c-3add-42df-9434-b46330bd4649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' filter-apply ')]</value>
      <webElementGuid>fdb1cac2-6c91-4184-82a1-08f8401c11e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' filter-apply ')]</value>
      <webElementGuid>b2006129-750e-4e47-a7ed-bd9f755da9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lọc sản phẩm' or . = 'Lọc sản phẩm')]</value>
      <webElementGuid>13b5cfea-0a41-4bd0-bc63-d53787749239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
