<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_priceMax</name>
   <tag></tag>
   <elementGuidId>33f6c69b-c284-4254-842c-17a1864080e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priceMax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'priceMax']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#priceMax</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36ce243c-be96-46de-90b6-a57241a66df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>d3d445aa-b373-47ba-82cd-c8d73f0d2ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price-slider</value>
      <webElementGuid>2bd9dd7b-8152-4f62-a063-efdfabd69572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priceMax</value>
      <webElementGuid>c289a5ae-ea77-4a0b-a3ac-8e150dfdfa66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f804af6f-9f85-41fd-8f22-2eb33227da58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>200000</value>
      <webElementGuid>c918ba98-0a0e-4ff4-b94e-f1feaf8f86de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>c93f444e-8c1b-4e6e-a81b-573ee9b8a452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>200000</value>
      <webElementGuid>c55c3ea7-edbe-4d06-bfc3-2451461516cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1e9188023541934c8d7f91b9441a33c2</value>
      <webElementGuid>a7cf526b-ad0e-42da-9650-c0bb45e6e3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'priceMax']</value>
      <webElementGuid>e1e327ef-cc55-4290-8d44-7d6171993745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'priceMax']</value>
      <webElementGuid>e24c5655-32bb-4843-9086-cbfb57931aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range' and @id = 'priceMax']</value>
      <webElementGuid>6f619a49-10de-4980-b964-b4af62e6f8b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
