<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_priceInputMax</name>
   <tag></tag>
   <elementGuidId>3a54b211-7e67-44c4-98c3-1425d7b41135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priceInputMax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'priceInputMax']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#priceInputMax</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f2d6ac3-6422-46d3-b001-1ed239898a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebd0bcc4-5559-444c-ac4c-76b641dd87cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priceInputMax</value>
      <webElementGuid>f5518b3c-ec3a-4498-8d25-af580b25d62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>200.000đ</value>
      <webElementGuid>52202a2a-56e9-46ae-ba88-f81e75ea7aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dacedde262c7ecc5308d65591d2425fd</value>
      <webElementGuid>30bf74fd-02d0-484f-9068-9aa7c9fe3d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'priceInputMax']</value>
      <webElementGuid>bd9033f1-4ece-4679-a05e-e111af0a3f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'priceInputMax']</value>
      <webElementGuid>17283313-3174-4a68-8e1a-86cc3ea42d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'priceInputMax']</value>
      <webElementGuid>1e390dae-fa11-4614-b01a-428e860cb567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
