<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xc nhn hu</name>
   <tag></tag>
   <elementGuidId>a140b642-1f57-41ea-8d0b-e033f65b46f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-confirm ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xác nhận huỷ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecf41650-fc7a-41fc-acf5-61db25608251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-confirm</value>
      <webElementGuid>5070c904-73ac-4d20-a1e0-c23073f6119c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>confirmCancelOrder()</value>
      <webElementGuid>e3a8d5a1-5df1-4d36-8ff5-b46dab266880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận huỷ</value>
      <webElementGuid>fd72bb99-0101-454d-a310-592da6df10d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a8fedf76a3d178bdc7512a19611796fe</value>
      <webElementGuid>efb2bb90-5962-4e73-9b72-4a26fafa2bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-confirm ')]</value>
      <webElementGuid>ab4e45d0-6395-4441-aa76-7948c8368ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-confirm ')]</value>
      <webElementGuid>2ef20c3b-2db9-4360-859c-f282a073dbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Xác nhận huỷ' or . = 'Xác nhận huỷ')]</value>
      <webElementGuid>c2692e50-f2c5-4f4d-8fe0-4bf282b399d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
