<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnAddLo</name>
   <tag></tag>
   <elementGuidId>6797d3db-5ec2-4566-923c-8f347b906d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddLo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnAddLo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Thêm lô thuốc&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4a53cc7-01d6-4179-ae42-780e4f0abc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>7ee5c005-e03b-46c8-a6b8-0325c64636f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddLo</value>
      <webElementGuid>e517d8da-4bd5-41fd-9c9e-176303615023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm lô thuốc</value>
      <webElementGuid>976afa51-1f72-48d1-84ce-7ba672df357c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-89c769e0949078955ac5f816825502a7</value>
      <webElementGuid>34735992-9fff-4033-8f90-9f45633912e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnAddLo']</value>
      <webElementGuid>74c58a65-3312-43c5-8549-b0019afddcf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnAddLo']</value>
      <webElementGuid>3a90e5c7-6362-4dfe-8f14-e209ee02fbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAddLo' and (text() = 'Thêm lô thuốc' or . = 'Thêm lô thuốc')]</value>
      <webElementGuid>703741b0-9986-4136-834b-bf7d62a31794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
