<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnSaveLo</name>
   <tag></tag>
   <elementGuidId>e55770fe-bb2e-480a-945c-c56bef13dc14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveLo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnSaveLo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Lưu lô thuốc&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aeff2d2b-4278-46c2-996f-2491c82f8394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ef90f8fc-ad44-4302-9f0f-32f3f08f4741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveLo</value>
      <webElementGuid>31f47e30-f6fe-4e6e-82d9-bf914f0c4f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lưu lô thuốc</value>
      <webElementGuid>db6435ca-bf3e-44ab-9f10-a0bcaf6cf544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0ebcb65cd750230684e427555d4b675d</value>
      <webElementGuid>f91a9bcf-bf33-439b-b9b2-8e3058484659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveLo']</value>
      <webElementGuid>43f38e77-3fc5-40b1-9710-fbf61db14746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveLo']</value>
      <webElementGuid>2daf4b3e-4f60-46aa-835e-b59f58555caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveLo' and (text() = 'Lưu lô thuốc' or . = 'Lưu lô thuốc')]</value>
      <webElementGuid>1513940a-b828-4705-b976-ba16ef0e282c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
