<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0</name>
   <tag></tag>
   <elementGuidId>d268b872-defd-4f2c-815e-b5aa940d0b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_soLuongTon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_soLuongTon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_soLuongTon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eafe6d3-c946-4c0b-99cf-ae64ee3427e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b37f82f8-babe-4c4d-850e-ace233197a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_soLuongTon</value>
      <webElementGuid>e470889d-96d1-4c7d-80c6-0dec9cb73197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>soLuongTon</value>
      <webElementGuid>0053f4a4-0777-4540-9c82-3245a18bfd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aafc2b4a-3f60-4893-87d4-8da4963e6cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c2abbd6-3386-4e3c-95ec-7fdb98614198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef19ee4a-3e3e-4542-9010-e9dc6c9bfaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4c114ba33dc8f56b5e4cf64d88ac07fd</value>
      <webElementGuid>7ad1a955-89ce-4208-a782-751a46e952d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_soLuongTon']</value>
      <webElementGuid>aaae8355-4985-46b8-a942-591ae2b47455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_soLuongTon']</value>
      <webElementGuid>0162fa7b-6f61-4be9-ab5e-570b4e23a6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'f_soLuongTon' and @name = 'soLuongTon' and @placeholder = '0']</value>
      <webElementGuid>ee7262f6-2cbb-4de2-aaf7-0192e128b84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
