<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_f_ngaySanXuat</name>
   <tag></tag>
   <elementGuidId>5bea19ca-7396-4704-aae2-b291811d0afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_ngaySanXuat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_ngaySanXuat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_ngaySanXuat</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0659000-c51d-493b-9da4-7a9f8da0e6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>f6215c51-990a-4fb9-aff6-ca05e69ba1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_ngaySanXuat</value>
      <webElementGuid>5ce9e40a-6e0b-4f66-8553-a49c66e02a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ngaySanXuat</value>
      <webElementGuid>b72bc177-041b-4f89-ae79-c1a3082e46df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b23f9d979ab877e503383c28deb22ac7</value>
      <webElementGuid>efca46b1-c50b-42aa-9bfe-225655a165ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_ngaySanXuat']</value>
      <webElementGuid>ca76511b-cba0-4eef-ac1a-7bae603269ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_ngaySanXuat']</value>
      <webElementGuid>25f5b7e0-697b-4bd4-ae52-d57e6d698b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'f_ngaySanXuat' and @name = 'ngaySanXuat']</value>
      <webElementGuid>14aa2685-fc96-4b98-8492-8d1649288e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
