<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_f_hanSuDung</name>
   <tag></tag>
   <elementGuidId>8bed7f61-83a3-43b3-8c33-39078d14a83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_hanSuDung</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_hanSuDung']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_hanSuDung</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6167eea8-29e8-4362-9fa1-6251cba94978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>a83d07c9-4f04-463f-8450-e624e1f266f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_hanSuDung</value>
      <webElementGuid>0a584ea4-fbb3-4559-b3f1-8656ce746134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hanSuDung</value>
      <webElementGuid>5a1b611a-6f2c-4af7-9f78-91c1f25cce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e7456e33c5e6f5ce5a129dda9298d398</value>
      <webElementGuid>ab2298f4-48bc-45fa-a2cf-3096cf85b781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_hanSuDung']</value>
      <webElementGuid>cd60b003-f27c-416e-87da-fe1080dcecef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_hanSuDung']</value>
      <webElementGuid>d7680e83-0936-4029-9151-40f822562b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'f_hanSuDung' and @name = 'hanSuDung']</value>
      <webElementGuid>1c1266a6-e3fe-460e-a897-89d4dced7597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
