<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0_1</name>
   <tag></tag>
   <elementGuidId>c190e49a-81ad-408f-ab26-e29bb9df7b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_giaNhap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_giaNhap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_giaNhap</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4268b955-fb6e-4637-9d33-44109cbcd48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9df1f139-effb-484d-aafb-199938826657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_giaNhap</value>
      <webElementGuid>3a2f21c8-bcad-4be0-8f28-24b026f53bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giaNhap</value>
      <webElementGuid>7c17a31c-e226-4f66-abe9-cbb6ad95acf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3254907-b39c-410c-9a44-0124285c7c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>eefac22a-b343-4232-a5dc-f76f3c8965d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>318f2f5d-9aea-458f-aabf-7dc46fa8bf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-88e07346905a3f038fce87666aff2211</value>
      <webElementGuid>b339f0d8-70a7-4026-a930-193000075be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_giaNhap']</value>
      <webElementGuid>d4806854-27c4-4169-a7e8-8c3836303b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_giaNhap']</value>
      <webElementGuid>5cdd751d-228b-4a57-b39c-7294cc794bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'f_giaNhap' and @name = 'giaNhap' and @placeholder = '0']</value>
      <webElementGuid>6be76ed7-8073-4d6a-b2cf-df7f1042581a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
