<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnResetFilter</name>
   <tag></tag>
   <elementGuidId>e539fceb-4575-42e4-9528-c140968ad599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnResetFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnResetFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đặt lại&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84a51643-a6b9-4dd3-b87d-49967bb326a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-ghost</value>
      <webElementGuid>c80d918a-a746-498d-8844-61903236307f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnResetFilter</value>
      <webElementGuid>2488da59-a985-4595-83a4-d82d29d657ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt lại</value>
      <webElementGuid>b39d0991-eac1-48df-88fd-5134a275d64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cbeb48adc72f1ac6d8a58a48d41886c9</value>
      <webElementGuid>d70228ce-efc3-46cf-b82f-46b79888ccac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnResetFilter']</value>
      <webElementGuid>9fea04bd-e416-46c0-ac13-e62c8a59130f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnResetFilter']</value>
      <webElementGuid>962a32e3-6b97-4d1b-ac17-b6a8948c738b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnResetFilter' and (text() = 'Đặt lại' or . = 'Đặt lại')]</value>
      <webElementGuid>5d144e3d-e1a6-4ba4-92ba-b6ea7336abde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
