<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnResetFilter</name>
   <tag></tag>
   <elementGuidId>a4227170-76c3-4c47-827b-520886d7f392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnResetFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnResetFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đặt lại&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a9e955c-e615-4a3e-b65e-6265637e5e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-ghost</value>
      <webElementGuid>14986025-0c91-488f-ad78-22efba811bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnResetFilter</value>
      <webElementGuid>6ed213e1-7a45-430c-85b6-9b0a6c7143af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt lại</value>
      <webElementGuid>ea21cd9c-7920-4b4d-9db9-ee3a521e89ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cbeb48adc72f1ac6d8a58a48d41886c9</value>
      <webElementGuid>73428a6c-3022-4dd6-a599-4bde133aa780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnResetFilter']</value>
      <webElementGuid>3b71c825-a006-496e-a351-2d0cc721f8f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnResetFilter']</value>
      <webElementGuid>48233d25-dcce-4487-bdc4-75a137fde066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnResetFilter' and (text() = 'Đặt lại' or . = 'Đặt lại')]</value>
      <webElementGuid>9e430d11-a8f7-4a32-99d7-9cd46a86a85a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
