<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnSaveThuoc</name>
   <tag></tag>
   <elementGuidId>1669b708-6676-4c0c-9b48-383896169ae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveThuoc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnSaveThuoc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Lưu dữ liệu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>897e4069-77c5-43b8-8da6-a69fd6e9088e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>e8f0cb9e-decc-4478-9017-80d9b04f8d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveThuoc</value>
      <webElementGuid>0f29e14e-fa1c-47c9-8914-8057ef8a3a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lưu dữ liệu</value>
      <webElementGuid>1774fc36-4b63-4b2e-80b0-ae7b4d4e98a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-00d9da3477f126b584f7c2ea73bb40d7</value>
      <webElementGuid>78d87b28-498b-4ad1-82c2-b3ca5e63b923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveThuoc']</value>
      <webElementGuid>0fcd1ec1-d9d6-4998-aa88-7ac38a1230da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveThuoc']</value>
      <webElementGuid>931b3a25-ee6c-40d9-bc7c-4745b8368838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveThuoc' and (text() = ' Lưu dữ liệu' or . = ' Lưu dữ liệu')]</value>
      <webElementGuid>81b01699-8e4c-41e8-a7ae-ea789e56b7bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
