<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_f_giaBan</name>
   <tag></tag>
   <elementGuidId>4319b2d3-256d-43ae-b115-c6185112ab5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_giaBan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_giaBan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_giaBan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b47021e5-eb4d-44f2-b22d-fa7c39800062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>361ca433-ca0c-4726-98bf-845449df5e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_giaBan</value>
      <webElementGuid>19288f2a-3489-460f-b923-930b7490f75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giaBan</value>
      <webElementGuid>eb998c21-61bc-473d-bf27-53005cafbd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-77fa6db839f7de557a7c090726c765c1</value>
      <webElementGuid>5068cb28-becd-4126-908a-77a72a37d380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_giaBan']</value>
      <webElementGuid>9ee961df-cbdc-493f-9678-42128fcc5b64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_giaBan']</value>
      <webElementGuid>c9e1d7db-1c3e-4267-a835-9672e6a7af13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'f_giaBan' and @name = 'giaBan']</value>
      <webElementGuid>6df8ad8d-4717-4500-a981-afb4b51753cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
