<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lc sn phm</name>
   <tag></tag>
   <elementGuidId>7db456ff-c7a6-4f29-b903-dcaa8c26b1f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.filter-apply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' filter-apply ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Lọc sản phẩm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e132171a-d16d-4bc9-9fc6-faca70890fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-apply</value>
      <webElementGuid>1fbb7e07-6b4b-405e-bf00-898a105a94bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>applyFilters()</value>
      <webElementGuid>6c1404b2-34f6-414f-917a-86db24900d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lọc sản phẩm</value>
      <webElementGuid>3e0537cc-58c0-4d5b-862b-2e905bc35127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e5a0ce4e4ff54b5c48bc4c8a1c1d283a</value>
      <webElementGuid>0c96e09e-1323-497b-9138-831f51eb6aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' filter-apply ')]</value>
      <webElementGuid>38da38d1-7018-4118-b88b-ec5e61ae4bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' filter-apply ')]</value>
      <webElementGuid>2edd9b72-f9a2-4157-8c22-8a45cc933cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lọc sản phẩm' or . = 'Lọc sản phẩm')]</value>
      <webElementGuid>b9ea631c-1cb1-4fa6-b230-c1234f65c020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
