<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Khng k n (OTC)</name>
   <tag></tag>
   <elementGuidId>6a58843c-c839-4c7d-90eb-ac2c978f689c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-rxtype=&quot;OTC&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-rxtype = 'OTC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Không kê đơn (OTC)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2b29417-a870-4b83-91d0-f94fd0bc375d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>474cc7ae-7dba-4bce-9fca-59f534f7b570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>t1</value>
      <webElementGuid>0e771db3-f724-45c2-b522-2957a460a46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rxtype</name>
      <type>Main</type>
      <value>OTC</value>
      <webElementGuid>f843f276-9d2a-4a53-9b2e-ed7d7c6d9793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-96e859f2b577b26ee7f810dd720a1410</value>
      <webElementGuid>b65454c7-4dd9-48a1-b325-1c44f8b230ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-rxtype = 'OTC']</value>
      <webElementGuid>64232d54-2f9c-4376-a53c-94d4dfe0df18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-rxtype = 'OTC']</value>
      <webElementGuid>dab888e0-e520-4181-a157-3aa54cf18dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 't1']</value>
      <webElementGuid>f40ec7f0-eac8-4be2-8cc8-aba608ff0179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
