<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnModalCancel</name>
   <tag></tag>
   <elementGuidId>30de4591-3d9f-47ce-b59d-a96c5d8a7c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnModalCancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnModalCancel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Hủy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf6a242f-e3d7-4a4c-b29d-3e37ba735c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-ghost</value>
      <webElementGuid>1259f68a-937a-4718-a1ff-59095e4306f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnModalCancel</value>
      <webElementGuid>b7f2dd85-26c9-4c8e-965a-7531cf69b728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hủy</value>
      <webElementGuid>56cbfd4d-2e99-4f16-a20b-fc370f1ab17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5fd198a75e8095af4ec977346a394ec5</value>
      <webElementGuid>e060b0e9-b2ac-4f94-82f0-9f2e038e2666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnModalCancel']</value>
      <webElementGuid>d169a839-fce7-41fe-bf8b-888cd8da872a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnModalCancel']</value>
      <webElementGuid>ce224405-4631-432e-9fe6-0604bd069530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnModalCancel' and (text() = 'Hủy' or . = 'Hủy')]</value>
      <webElementGuid>30bd2b46-1ac9-4b7f-a8de-b14a63d49c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
