<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_f_soDienThoai</name>
   <tag></tag>
   <elementGuidId>ad02c719-4dfa-4d6a-9691-85962007af64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_soDienThoai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_soDienThoai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_soDienThoai</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>365bb800-5789-4f74-b6a2-e854885a4a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>581963e9-b326-4045-8b0a-1b6271385dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_soDienThoai</value>
      <webElementGuid>8350f7be-b77f-4443-b85a-d6a3a7aef130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3e2c267d79711f70714f885ecb175aff</value>
      <webElementGuid>43600c6f-13fe-4705-b050-e710e661ed91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_soDienThoai']</value>
      <webElementGuid>984332a5-69ed-4197-bb02-912e9d807e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_soDienThoai']</value>
      <webElementGuid>09869cb0-6b40-4d5f-a4fd-5bab804f0e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'f_soDienThoai']</value>
      <webElementGuid>19f66630-e359-4b77-8a16-5f88e115978d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
