<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_f_hoTen</name>
   <tag></tag>
   <elementGuidId>80be21fc-f953-4f70-9684-868507980659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_hoTen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'f_hoTen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f_hoTen</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d151f49-1654-4c5c-a84a-f514390d56bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68a2dcf0-6556-4f53-88c0-4d654d1ce9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_hoTen</value>
      <webElementGuid>9475366c-6ae8-4cef-9ea9-f413d768beb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-41a76aa20da37951d264c3f10122924a</value>
      <webElementGuid>ef80ab87-3366-4564-8116-b2dbb5a37c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'f_hoTen']</value>
      <webElementGuid>c4e4577a-7aea-4f72-b308-35e995b6ee08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'f_hoTen']</value>
      <webElementGuid>6c7b7a91-8b55-4c10-95f6-ffc469572ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'f_hoTen']</value>
      <webElementGuid>4386d08f-286f-40a0-b767-5a653ecf3f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
