<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnSaveRole</name>
   <tag></tag>
   <elementGuidId>fc8b11db-7c0b-47f3-828a-dd6eb7e648e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnSaveRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xác nhận cấp quyền&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e92a395-6a0f-4acf-b77b-0e3121e21efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c86ea1e8-e1bf-482e-9752-5333ec45abe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveRole</value>
      <webElementGuid>292b79ad-4977-4daa-90de-f3b14529a05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận cấp quyền</value>
      <webElementGuid>3d535c83-976b-4b2d-b0b9-0b39c81baa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-57dead48b99ee6ba4ee76496ee4f4bfd</value>
      <webElementGuid>16451f80-adaf-4760-bd71-d8d3b295aa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveRole']</value>
      <webElementGuid>4a16e88e-260b-45c0-b557-33edbd25a78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveRole']</value>
      <webElementGuid>b8dc1f28-c6a4-44b2-b437-8bc4d2bffd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveRole' and (text() = 'Xác nhận cấp quyền' or . = 'Xác nhận cấp quyền')]</value>
      <webElementGuid>7690c79f-98dc-4f21-8552-20e405fc3a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
