<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btnSaveRole</name>
   <tag></tag>
   <elementGuidId>cbdc9da5-500b-4cde-887b-34074512b102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnSaveRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xác nhận cấp quyền&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f86e80a7-6c4c-49f9-aeeb-48a52250ce9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>34511273-a6e7-4d31-b2c8-e779fcf06bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveRole</value>
      <webElementGuid>8bce3c09-2e6b-49f6-8237-d98657b2388b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận cấp quyền</value>
      <webElementGuid>18fb9b3c-64ee-4f5e-adc6-e2ac38d2e3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-57dead48b99ee6ba4ee76496ee4f4bfd</value>
      <webElementGuid>822ddc57-824a-43de-a994-628a05e47537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveRole']</value>
      <webElementGuid>c71d2755-ba41-4e16-8da7-7b4a7a65f143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnSaveRole']</value>
      <webElementGuid>36abadf4-227f-4ee8-9f49-21c60d336cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveRole' and (text() = 'Xác nhận cấp quyền' or . = 'Xác nhận cấp quyền')]</value>
      <webElementGuid>f8da6fce-19da-453a-9e0c-08ada40dcca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
