<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tip tc mua hng</name>
   <tag></tag>
   <elementGuidId>26ac679f-7b2e-4770-914a-32f05b8ec2b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.back-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' back-btn ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Tiếp tục mua hàng&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08d7a739-f831-42bb-9732-2f30402bc813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-btn</value>
      <webElementGuid>79e97e68-d504-4291-a3f6-9ee83b946f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost/BanThuoc/public/khachHang/thuoc</value>
      <webElementGuid>95773997-83ae-4943-a08f-8bcf298c45c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tiếp tục mua hàng</value>
      <webElementGuid>947e9ed9-34f4-4165-9f5a-a6fcad7229f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-620e4f6a8e70a8cc3808d243835e0188</value>
      <webElementGuid>4e55e2a7-2c73-48b0-964e-1e549a43c14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' back-btn ')]</value>
      <webElementGuid>bd6bb9c1-ef82-4236-b828-dcd5df9c8766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' back-btn ')]</value>
      <webElementGuid>2d110dcb-961c-4738-9765-dbc4c66853b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/BanThuoc/public/khachHang/thuoc' and (text() = ' Tiếp tục mua hàng' or . = ' Tiếp tục mua hàng')]</value>
      <webElementGuid>a87996ce-2ad3-49cf-9d7f-6204c44d2bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
