<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_checkoutBtn</name>
   <tag></tag>
   <elementGuidId>7acac419-2609-41a6-b303-8f2d5382d006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'checkoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Mua hàng&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>054ab2d9-385c-4ad2-8d7f-cd05a01da3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4a9ee4b-06e4-467e-9027-5c1dbbd26512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>b0e1845f-8082-4df2-93f4-bb8f6ee76756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkoutBtn</value>
      <webElementGuid>ca34e1d7-3cec-4ea0-8872-c21be8f42726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mua hàng</value>
      <webElementGuid>0a427bdf-d3e8-4242-ad62-71120c4b1ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c4ff22d8fb95463a2ad86f7726221d78</value>
      <webElementGuid>567bd151-6d84-486b-bf61-02cda05d308c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'checkoutBtn']</value>
      <webElementGuid>acbe8ba3-c7d4-429c-8c27-6ae064548439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'checkoutBtn']</value>
      <webElementGuid>ead6cc4c-eec0-4811-8920-8558039ada7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'checkoutBtn' and (text() = 'Mua hàng' or . = 'Mua hàng')]</value>
      <webElementGuid>91136256-63fb-4495-9c77-c955b3a625ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
