<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selectAll</name>
   <tag></tag>
   <elementGuidId>c6c57e58-5061-49c0-b66a-d6f61d9ee0db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectAll</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'selectAll']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'selectAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Chọn mua tất cả (3/3)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbc5f4f6-c895-40dc-b3f4-5d4bd4d7ff74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>56e1a281-befa-4750-a390-6ed1d5accf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectAll</value>
      <webElementGuid>876f9ffc-9b3c-4eca-a715-3b6b74b737ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c788e8718271ab396d6b9a8be2042035</value>
      <webElementGuid>35232597-e8d0-4a06-a1fe-06c59126eab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'selectAll']</value>
      <webElementGuid>c118c85f-4dd9-4050-be77-fe7dfb9e1179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'selectAll']</value>
      <webElementGuid>67bab26c-e70f-4ab6-a13d-91c448ad4a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectAll']</value>
      <webElementGuid>b224c3d1-6b6f-46e7-8ee9-f320aa6a7535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
