<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_menuToggle</name>
   <tag></tag>
   <elementGuidId>0da539ef-884d-4b96-86fc-e958e5a9fc98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuToggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'menuToggle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menuToggle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce6db35c-bcbe-4856-ac1e-7f264fd3d726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-toggle</value>
      <webElementGuid>7ef26ecc-049e-496d-87e1-a4c03995e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuToggle</value>
      <webElementGuid>48a1d06c-a653-49d6-98f0-a271bdbff670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                 Danh sách hàng hóa            </value>
      <webElementGuid>bd2a8971-e1cc-4ae3-be5e-24aa16990ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-70d3d28a884e4ea4b5f9c7403969a090</value>
      <webElementGuid>8d744944-f320-466b-9897-af49c2071af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'menuToggle']</value>
      <webElementGuid>8a929f3e-6b4d-4bb0-9c93-d72898bfc5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'menuToggle']</value>
      <webElementGuid>2e52bccd-4d9d-4689-bb29-3cbee8735244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'menuToggle' and (text() = '
                 Danh sách hàng hóa            ' or . = '
                 Danh sách hàng hóa            ')]</value>
      <webElementGuid>f7228bef-4a3e-4d75-93d3-9f9d89530012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
