<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S nh, tn ng, phng, qun, tnh thn</name>
   <tag></tag>
   <elementGuidId>e5ad2aca-fc82-4d2a-b211-a913f1857a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mDetail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'mDetail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Số nhà, tên đường, phường, quận, tỉnh thành...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>279eb824-eedd-4710-9da0-d937eb088d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b115f40-0887-41bd-91bc-17eba9cb4952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mDetail</value>
      <webElementGuid>fd14c2b5-a7a3-4ef1-a143-1b7da27d58c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số nhà, tên đường, phường, quận, tỉnh thành...</value>
      <webElementGuid>a6c08741-6854-4bad-b6f5-f3fb0bac16be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6f1b3014c866ab7bb326cdcca61c3609</value>
      <webElementGuid>1e17fff8-4d1e-405c-91fc-ed5de2efd10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'mDetail']</value>
      <webElementGuid>504f443e-c3a7-444d-b64a-cfa1d9d575b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'mDetail']</value>
      <webElementGuid>802f2595-9208-447e-a19d-ad3e89b98a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mDetail' and @placeholder = 'Số nhà, tên đường, phường, quận, tỉnh thành...']</value>
      <webElementGuid>cf66c93f-cc43-485c-917e-90627855862b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
