<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VD_ Nh ring, C quan, Nh ni, Kho hng</name>
   <tag></tag>
   <elementGuidId>b2780e06-f462-47b7-a811-330f38a83146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'mLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;VD: Nhà riêng, Cơ quan, Nhà nội, Kho hàng...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccee1afa-ba97-4c15-a18f-eca04a6e00b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f91c7cc7-d47e-4595-8f89-4884b4f4df4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mLabel</value>
      <webElementGuid>2cdfe6ee-0676-437d-8e41-3f47aabda10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>VD: Nhà riêng, Cơ quan, Nhà nội, Kho hàng...</value>
      <webElementGuid>94b3e5bb-1380-4f06-aec9-39a253a1ff04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dce029f4d73ced863ab8fbbf08331ab0</value>
      <webElementGuid>eac97baf-ddc1-4f4a-b826-8c265be61d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'mLabel']</value>
      <webElementGuid>fd8f16b8-ec14-47d4-b476-0c717a8630cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'mLabel']</value>
      <webElementGuid>b4d1441f-faf4-42e8-b5d6-56215f76f5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mLabel' and @placeholder = 'VD: Nhà riêng, Cơ quan, Nhà nội, Kho hàng...']</value>
      <webElementGuid>33b52f34-a87f-48bd-b034-9223af1073a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
