<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_overlay</name>
   <tag></tag>
   <elementGuidId>b9d6f87e-14d2-4f7f-9550-8a1883dda88d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a779a630-57aa-4026-9635-0559131d0a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay open</value>
      <webElementGuid>61a729e9-7e14-4bb5-a283-bcf9a649b07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>b409c91f-ac70-4439-99e9-68f15893dd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1ad3445d49fda61670cdc0359089ee8e</value>
      <webElementGuid>2f3b3b31-5434-4de3-8fc2-f7dbcd6ca309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'overlay']</value>
      <webElementGuid>d2d7531a-5093-4dec-8824-eba846c752c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'overlay']</value>
      <webElementGuid>f37ce559-f690-4a34-8bea-87e7fa6a5ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'overlay']</value>
      <webElementGuid>790f25cd-4634-4f91-a5e2-e0a98b11cfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
